test_that("input validation", {
  expect_error(Grad(x = 1:4, FUN = "rubbish"), "must be a function")
  expect_error(Grad(x = 1:4, FUN = sum, h = c(0.01, 0.02)), "must have length")
  expect_error(Grad(x = 1:4, FUN = sum, side = c(0, 1, 2, -2)), "must contain values")
  expect_error(Grad(x = 1:4, FUN = sum, h = 0), "must be positive")
  expect_error(Grad(x = 1:4, FUN = sum, h = -0.001), "must be positive")
  expect_error(Grad(x = 1:4, FUN = function(x) "0.1"), "numeric values only")
  expect_error(Grad(x = 1:4, FUN = sum, side = c(-1, 1)), "'side' argument must")
  expect_error(Grad(x = 1:4), "Pass the function")
  expect_error(Grad(x = 1:4, FUN = sum, deriv.order = c(1, 2)), "'deriv.order' must have length")
  expect_error(Grad(x = 1:4, FUN = sum, acc.order = c(1, 2)), "'acc.order' must have length")
  expect_error(Grad(1:4, sin), "argument order")
})
